# Generated by Django 4.2.5 on 2023-10-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
    ]
