# Generated by Django 4.2.5 on 2023-10-03 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_libro_autor_alter_libro_editorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
    ]
